### ISSUE TITLE
Singlton Example

### ISSUE THREAD

**Issue by phikal** [abuseofnotation/category-theory-illustrated#26]
In the "Singleton Set" section it says:

> The set of books written by the American writer Harper Lee and published during her lifetime is a singleton set - she has published just one novel.

Which isn't quite true, since 2015 she published ["Go Set a Watchman"](https://en.wikipedia.org/wiki/Go_Set_a_Watchman). 

I know this is being pedantic and not the point of the explanation, but I guess it _could_ confuse someone who knows a lot more about American literature than set theory.

**Comment by AlexPl292** [comment]
On a sad note, I also would like to add that "The set of queens of England" is now not a "singleton set", but an "empty set".

**Comment by abuseofnotation** [comment]
I rewrote the example about the queens of England and decided to remove the second example. 

The example with the king/queen is good because the king/queen is one by definition (the one with the capital is good too, but it is conceptually very similar to the one with the one about the kings)

Thanks @phikal, for the suggestions.
